#!/bin/sh

# check that a directory name was given
if [ $# -le 1 ]; then
  echo usage: runBDIM proc_num work_dir restart_dir
  exit 1
fi

# make the dir
mkdir $2
rm $2/fort.?
rm $2/fort.??
rm $2/fort.???
rm $2/fort.????

# set up inputs
cp $MGLHOME/bin/exec_BDIM $2/.
cp inp.* $2/.
if [ $# -eq 3 ]; then
    cp $3/restart.zip $2/initial.zip
    unzip $3/restart.zip -d $2
#    cp $3/out.geom $2/inp.geom
fi

# cd and move tecplot stuff
cd $2
cp ../tecplot/* .

# run the code
if [ $1 -eq 0 ]; then
    ./exec_BDIM
else
    mpiexec -n $1 ./exec_BDIM
fi

echo "runBDIM" $2 ": simulation complete"

# run the post processing scripts and macros
./runStat
zip -m restart fort.[1-2]???
nice ./runTec body.mcr lam2.mcr
nice ./runTec 'lam2.lay avi.mcr'
mv movie.avi lam2.avi
nice ./runTec 'lam2_zoom.lay avi.mcr'
mv movie.avi lam2_zoom.avi
nice ./runTec 'lam2_top.lay png.mcr'
wait

echo "runBDIM" $2 ": visualization complete"
./runZip
rm batch.log junk
echo "runBDIM" $2 ": cleanup complete"

exit 0