#!/bin/sh

# check that a directory name was given
if [ $# -le 1 ]; then
  echo usage: runBDIM proc_num work_dir restart_dir
  exit 1
fi

# make the dir
mkdir $2
rm $2/fort.?
rm $2/fort.??
rm $2/fort.???
rm $2/fort.????

# set up inputs
cp exec_BDIM $2/.
cp inp.* $2/.
cp *IGS $2/.
if [ $# -eq 3 ]; then
    cp $3/fort.1??? $2/.
    cp $3/fort.2??? $2/.
fi

# cd and move tecplot stuff
cd $2
cp ../tecplot/* .

# run the code
if [ $1 -eq 0 ]; then
    ./exec_BDIM &
else
    mpiexec -n $1 ./exec_BDIM &
fi

wait 

# run the post processing scripts and macros
zip  vort_txt.zip fort.2?? &
zip  lam2_txt.zip fort.4?? &
wait
nice ./exec_tec 
nice ./exec_tec body.mcr lam2.mcr
nice ./exec_tec 'lam2.lay avi.mcr'
nice ./exec_tec 'lam2_top.lay png.mcr'
zip -m body.zip fort.1??.plt &
zip -m pres.zip fort.3??.plt &
zip -m lam2.zip fort.4??.plt &
zip -m vort.zip fort.2??.plt &
wait
rm batch.log junk
echo "complete"
exit 0