#!/bin/sh

# check that a directory name was given
if [ $# -le 1 ]; then
  echo usage: runBDIM proc_num work_dir restart_dir
  exit 1
fi

# make the dir
mkdir $2
rm $2/fort.[1-9]*

# set up inputs
cp exec_BDIM $2/.
cp inp.* $2/.
cp *IGS $2/.
if [ $# -eq 3 ]; then
    cp $3/fort.1??? $2/.
    cp $3/fort.2??? $2/.
fi

# cd and move tecplot stuff
cd $2
cp ../tecplot/* .

# run the code
if [ $1 -eq 0 ]; then
    ./exec_BDIM &
else
    mpiexec -n $1 ./exec_BDIM &
fi

wait 

# run the post processing scripts and macros
rm fort.[1-9]?[0-3,5-9]
nice ./exec_tec line.mcr bodyAndPress.mcr
nice ./exec_tec 'pressure.lay png.mcr'
mv fort.404.plt vort.plt
mv fort.204.plt velo.plt
nice ./exec_tec 'ke.lay int.mcr'
zip -m restart fort.[1-2]???
zip -m vort fort.3???
zip -m velo fort.4???
# rm fort.*
wait
echo "complete"
exit 0