#!/bin/sh

# check that a directory name was given
if [ $# -le 1 ]; then
  echo usage: runBDIM proc_num work_dir restart_dir
  exit 1
fi

# make the dir
mkdir $2
rm $2/fort.?
rm $2/fort.??
rm $2/fort.???
rm $2/fort.????

# set up inputs
cp $MGLHOME/bin/exec_BDIM $2/.
cp inp.* $2/.
if [ $# -eq 3 ]; then
    cp $3/restart.zip $2/initial.zip
    unzip $3/restart.zip -d $2
    mv $2/out.geom $2/inp.geom
fi

# cd and move tecplot stuff
cd $2
cp ../tecplot/* .

# run the code
if [ $1 -eq 0 ]; then
    ./exec_BDIM
else
    mpiexec -n $1 ./exec_BDIM
fi

wait 
echo "runBDIM" $2 ": simulation complete"

# pack up restart files
zip -m restart fort.[1-2]??? out.geom 1>/dev/null

# run the post processing scripts and macros
./runStat
rm fort.[1-9]?[0-2,4-9]
nice ./runTec line.mcr
rm fort.103.plt; mv fort.203.plt velo.plt; mv fort.303.plt pres.plt; mv fort.403.plt vort.plt
./runZip
nice ./runTec 'BComega.lay avi.mcr'
nice ./runTec 'omega.lay pngShift.mcr'
echo "complete"
exit 0