#!MC 1120
# Created by Tecplot 360 build 11.3.29.563
$!OPENLAYOUT  "movie.lay"
$!EXPORTSETUP EXPORTFORMAT = AVI
$!EXPORTSETUP IMAGEWIDTH = 800
$!EXPORTSETUP EXPORTFNAME = 'movie.avi'
$!ANIMATETIME 
  STARTTIME = 8.6
  ENDTIME = 11.4
  SKIP = 1
  CREATEMOVIEFILE = YES
  LIMITSCREENSPEED = NO
  MAXSCREENSPEED = 12

