#!MC 1120
# Created by Tecplot 360 build 11.3.29.563

$!EXPORTSETUP EXPORTFORMAT = AVI
$!EXPORTSETUP IMAGEWIDTH = 800
$!EXPORTSETUP EXPORTFNAME = 'movie.avi'
$!ANIMATETIME 
  STARTTIME = 0
  ENDTIME = 100
  SKIP = 1
  CREATEMOVIEFILE = YES
