source('../analysis.R')
p = params('./')
tData = forces(p$folder,p$amp,p$freq,3)

x = seq(0,1,0.01); y = max(tData$lift)
q = qplot(phase,lift,data=tData,alpha=I(0.05),color=I('blue'))+geom_point(aes(y=liftf),color='red',alpha=0.05)+geom_line(data=data.frame(phase=x,lift=y*cos(2*pi*x)),linetype=2)+ylab(expression(C[L]))
ppng(q,"ClPhase.png")

fData = subset(myfft(tData$lift,tData$time),freq<1)
ffData = subset(myfft(tData$liftf,tData$time),freq<1)
q = qplot(freq,Mod(coeffs),data=fData,geom='line',color=I('blue'))+geom_line(data=ffData,color='red')
ppdf(q,"ClMod.pdf")
q = qplot(freq,Re(coeffs),data=fData,geom='line',color=I('blue'))+geom_line(data=ffData,color='red')
ppdf(q,"ClRe.pdf")
q = qplot(freq,Im(coeffs),data=fData,geom='line',color=I('blue'))+geom_line(data=ffData,color='red')
ppdf(q,"ClIm.pdf")
