#!MC 1120
# Created by Tecplot 360 build 11.3.29.563

$!EXPORTSETUP EXPORTFORMAT = AVI
$!EXPORTSETUP IMAGEWIDTH = 720
$!EXPORTSETUP EXPORTFNAME = 'movie.avi'
$!ANIMATETIME 
  STARTTIME = 0.0
  ENDTIME = 15
  SKIP = 1
  CREATEMOVIEFILE = YES
  LIMITSCREENSPEED = NO
  MAXSCREENSPEED = 12
