#!MC 1120
# Created by Tecplot 360 build 11.3.29.563
$!CREATEISOZONES 
$!WRITEDATASET  "body.plt"
  INCLUDETEXT = NO
  INCLUDEGEOM = NO
  INCLUDECUSTOMLABELS = NO
  ASSOCIATELAYOUTWITHDATAFILE = NO
  ZONELIST =  [2]
  VARPOSITIONLIST =  [1-3]
  BINARY = YES
  USEPOINTFORMAT = NO
  PRECISION = 9
