#!/bin/sh

# check that a directory name was given
if [ $# -le 1 ]; then
  echo usage: runBDIM proc_num work_dir restart_dir
  exit 1
fi

# make the dir
mkdir $2
rm $2/*

# set up inputs
cp exec_BDIM $2/.
cp inp.* $2/.
cp tecplot/* $2/.

# cd and unzip restart stuff
cd $2
if [ $# -eq 3 ]; then
    unzip ../$3/rest.zip
fi

# run the code
echo "running"
if [ $1 -eq 0 ]; then
    nice -n 20 ./exec_BDIM &
else
    nice -n 20 mpiexec -n $1 ./exec_BDIM &
fi

wait 

# run the post processing scripts and macros
nice ./exec_tec 'FI.mcr' 'lam2.mcr'
#nice ./exec_tec 'HD.lay HD.mcr'
nice ./exec_tec 'veloAndFI.lay avi.mcr'
zip -m body fort.1??.plt
zip -m velo fort.2??.plt
zip -m lam2 fort.4??.plt
zip -m fint fort.5??.plt
zip -m rest fort.????
wait
echo "complete"
say "complete"
exit 0