#!/bin/sh

# check that a directory name was given
if [ $# -le 1 ]; then
  echo usage: runBDIM proc_num work_dir restart_dir
  exit 1
fi

# make the dir
mkdir $2
rm $2/fort.?
rm $2/fort.??
rm $2/fort.???
rm $2/fort.????

# set up inputs
cp exec_BDIM $2/.
cp inp.* $2/.
cp *.IGS $2/.
if [ $# -eq 3 ]; then
    cp $3/fort.1??? $2/.
    cp $3/fort.2??? $2/.
fi

# cd and move tecplot stuff
cd $2
cp ../tecplot/* .

# run the code
if [ $1 -eq 0 ]; then
    ./exec_BDIM &
else
    mpiexec -n $1 ./exec_BDIM &
fi

wait 

# run the post processing scripts and macros
nice ./exec_tec bodyInfo.mcr
nice ./exec_tec fint.mcr lam2.mcr 
nice ./exec_tec 'dp.lay avi.mcr'
zip -m body fort.1??.plt &
zip -m velo fort.2??.plt &
zip -m pres fort.3??.plt &
zip -m lam2 fort.4??.plt &
zip -m restart fort.1??? &
zip -m restartFint fort.2??? &
wait
echo "complete"
exit 0