#!/bin/sh

# preplot all files
for i in fort.[1-9][0-9][0-9]; do
    if  [ `ls $i | grep $i     -c` -ne 0 ]; then
    if  [ `ls $i | grep $i.plt -c` -eq 0 ]; then
	echo preplot: $i
	preplot $i $i.plt >> junk
	if  [ $? -ne 0 ]; then
	    echo exec_tec: problem with $i
	    exit 2
	fi
	if  [ `ls | grep $i.plt -c` -eq 1 ]; then
	    rm $i
	fi
    fi;fi
done

# run any macros
for i; do
    echo exec_tec: macro $i
    tec360 -b $i >> junk
    if  [ `grep Err batch.log -c` -ne 0 ]; then
	echo exec_tec: problem with macro
	exit 3
    fi
done

# clean up
rm batch.log junk

exit 0