#!/bin/sh
function archiveDIR
{
    pwd
    for i in 1 2 3 4 5 6 7 8 9; do
	ls fort.$i??.plt 2>/dev/null
	zip -m tec$i fort.$i??.plt 1>/dev/null
    done
    ls fort.[1-2]??? 2>/dev/null
    zip -m restart fort.[1-2]??? 1>/dev/null
    ls fort.1[0-6] 2>/dev/null
    zip -m log fort.1[0-6] 1>/dev/null

    ls -1 -d */ 2>/dev/null | while read LINE; do 
	cd $LINE
	archiveDIR
	cd ../
    done
}
archiveDIR
echo "runZip:complete"
exit 0