#!/bin/sh

# check that a directory name was given
if [ $# -le 1 ]; then
  echo usage: runBDIM proc_num work_dir restart_dir
  exit 1
fi

# make the dir
mkdir $2
rm $2/fort.?
rm $2/fort.??
rm $2/fort.???
rm $2/fort.????

# set up inputs
cp exec_BDIM $2/.
cp inp.* $2/.
if [ $# -eq 3 ]; then
    cp $3/fort.1??? $2/.
    cp $3/fort.2??? $2/.
    cp $3/inp.geom $2/.
    cp $3/inp.IGS $2/.
    tail -n 2 $3/fort.10 > $2/inp.force
fi

# cd and move tecplot stuff
cd $2
cp ../tecplot/* .

# run the code
if [ $1 -eq 0 ]; then
    ./exec_BDIM &
else
    mpiexec -n $1 ./exec_BDIM &
fi

wait 

# run the post processing scripts and macros
./runStat
nice ./runTec body.mcr lam2.mcr &
wait
./runTec 'avi.mcr lam2.lay'
mv movie.avi lam2.avi
./runZip
echo "runBDIM:complete"
exit 0