#!/bin/sh

# check that a directory name was given
if [ $# -le 1 ]; then
  echo usage: runBDIM proc_num work_dir restart_dir
  exit 1
fi

# make the dir
mkdir $2

# set up inputs
cp exec_BDIM $2/.
cp inp.* $2/.
if [ $# -eq 3 ]; then
    cp $3/fort.1??? $2/.
fi

# cd and move tecplot stuff
cd $2
cp ../tecplot/exec_tec .
cp ../tecplot/*.mcr .
cp ../tecplot/*.lay .

# run the code
if [ $1 -eq 0 ]; then
    ./exec_BDIM
else
    mpiexec -n $1 ./exec_BDIM
fi

# run the post processing scripts and macros
./exec_tec 'bod.mcr' 'cfl.lay png.mcr'
mv image.png cfl.png
./exec_tec 'forces.lay png.mcr'
mv image.png forces.png
./exec_tec 'lam2.lay png.mcr'
mv image.png lam2.png

