#!/bin/sh
grep 'final:' fort.8 | sed s/'final:'// > mgs.txt
R CMD BATCH --slave square.R
gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=report.pdf lift.pdf drag.pdf CFL.pdf res.pdf itr.pdf > /dev/null
xdg-open report.pdf
rm mgs.txt lift.pdf drag.pdf CFL.pdf res.pdf itr.pdf 
echo "runStat:complete"
exit 0
